import express from "express";
import cors from "cors";
import cron from "node-cron";
import dotenv from "dotenv";
import { createClient } from "@supabase/supabase-js";
dotenv.config();
const app=express();app.use(cors());app.use(express.json());
const supabase=createClient(process.env.SUPABASE_URL||"https://example.supabase.co",process.env.SUPABASE_SERVICE_ROLE_KEY||"missing-key",{auth:{persistSession:false}});
const usernameFromUrl=(url="")=>{const m=String(url).match(/@([A-Za-z0-9._-]+)/);return m?`@${m[1]}`:""};
const fallback=(url,msg="Manual verification needed")=>{const username=usernameFromUrl(url);const name=username.replace("@","").replace(/[._-]/g," ")||"Unknown Creator";return{username,name,profile_image:`https://api.dicebear.com/8.x/initials/svg?seed=${encodeURIComponent(name)}`,followers:0,total_likes:0,video_count:0,avg_likes:0,engagement:0,confidence:45,message:msg}};
async function scrapeTikTok(url){const username=usernameFromUrl(url);if(!username)throw new Error("Invalid TikTok profile URL");try{const r=await fetch(url,{headers:{"User-Agent":"Mozilla/5.0","Accept-Language":"en-US,en;q=0.9"}});const html=await r.text();const clean=v=>v?v.replaceAll("\\u002F","/").replaceAll("\\/","/"):"";const followers=Number(html.match(/"followerCount":(\d+)/)?.[1]||0);const total_likes=Number(html.match(/"heartCount":(\d+)/)?.[1]||html.match(/"likesCount":(\d+)/)?.[1]||0);const video_count=Number(html.match(/"videoCount":(\d+)/)?.[1]||0);const name=html.match(/"nickname":"(.*?)"/)?.[1]||username.replace("@","");const profile_image=clean(html.match(/"avatarLarger":"(.*?)"/)?.[1]||html.match(/"avatarMedium":"(.*?)"/)?.[1]||"");if(!followers&&!total_likes&&!video_count&&!profile_image)return fallback(url,"TikTok page loaded but metrics were not found");const avg_likes=video_count?Math.round(total_likes/video_count):0;const engagement=followers?Number(((avg_likes/followers)*100).toFixed(2)):0;return{username,name,profile_image,followers,total_likes,video_count,avg_likes,engagement,confidence:70,message:"Public TikTok data extracted"}}catch(e){return fallback(url,e.message)}}
function scores(d){const trust=Math.min(100,Math.round(Number(d.engagement||0)*4+Number(d.confidence||0)*.6+20));return{trust,audience:trust,fit:trust,brandSafety:75}}
function creatorPayload(url,d,meta={}){const s=scores(d);return{profile_url:url,username:d.username,name:d.name,profile_image:d.profile_image,country:meta.country||"Ethiopia",city:meta.city||"",region:meta.region||meta.city||meta.country||"Ethiopia",category:meta.category||"Food",language:meta.language||"Amharic",followers:d.followers||0,total_likes:d.total_likes||0,video_count:d.video_count||0,avg_likes:d.avg_likes||0,engagement:d.engagement||0,confidence:d.confidence||0,trust_score:s.trust,brand_safety_score:s.brandSafety,audience_quality_score:s.audience,campaign_fit_score:s.fit,verified_status:meta.verifiedStatus||"Unverified",influencer_current_state:meta.influencerCurrentState||"Active",influencing_level:meta.influencingLevel||"Medium",admin_intelligence_note:meta.adminIntelligenceNote||"",campaign_history:meta.campaignHistory||"",trend_participation:meta.trendParticipation||"",contact_status:meta.contactStatus||"locked",contact_email:meta.contactEmail||"",contact_phone:meta.contactPhone||"",data_source:d.followers?"scraper_sync":"fallback_public_record",sync_mode:meta.syncMode||"auto_10_min",sync_status:d.followers?"synced":"partial",message:d.message,last_synced_at:new Date().toISOString(),next_sync_at:new Date(Date.now()+10*60*1000).toISOString(),updated_at:new Date().toISOString()}}
function mapCreator(r){return{id:r.id,profileUrl:r.profile_url,username:r.username,name:r.name,profileImage:r.profile_image,country:r.country,city:r.city,region:r.region,category:r.category,language:r.language,followers:Number(r.followers||0),totalLikes:Number(r.total_likes||0),videoCount:Number(r.video_count||0),avgLikes:Number(r.avg_likes||0),engagement:Number(r.engagement||0),growth:Number(r.growth||0),confidence:Number(r.confidence||0),trustScore:Number(r.trust_score||0),brandSafetyScore:Number(r.brand_safety_score||0),audienceQualityScore:Number(r.audience_quality_score||0),campaignFitScore:Number(r.campaign_fit_score||0),verifiedStatus:r.verified_status,influencerCurrentState:r.influencer_current_state,influencingLevel:r.influencing_level,adminIntelligenceNote:r.admin_intelligence_note,campaignHistory:r.campaign_history,trendParticipation:r.trend_participation,contactStatus:r.contact_status,contactEmail:r.contact_email,contactPhone:r.contact_phone,dataSource:r.data_source,syncStatus:r.sync_status,lastSyncedAt:r.last_synced_at,nextSyncAt:r.next_sync_at,message:r.message}}
async function saveHistory(id,d){await supabase.from("creator_metric_history").insert({creator_id:id,followers:d.followers||0,total_likes:d.total_likes||0,video_count:d.video_count||0,engagement:d.engagement||0,trust_score:scores(d).trust})}
async function addSyncLog(id,username,type,status,message){await supabase.from("sync_logs").insert({creator_id:id,username,type,status,message})}
app.get("/",(req,res)=>res.json({service:"AfriCreator IQ V13 Fixed Backend",status:"running"}));
app.post("/api/import-tiktok",async(req,res)=>{try{const{profileUrl,...meta}=req.body||{};if(!profileUrl)return res.status(400).json({success:false,message:"profileUrl is required"});const scraped=await scrapeTikTok(profileUrl);const{data,error}=await supabase.from("creators").upsert(creatorPayload(profileUrl,scraped,meta),{onConflict:"profile_url"}).select().single();if(error)return res.status(500).json({success:false,error:error.message});await saveHistory(data.id,scraped);await addSyncLog(data.id,data.username,"import_tiktok",data.sync_status,scraped.message);res.json({success:true,creator:mapCreator(data)})}catch(e){res.status(500).json({success:false,error:e.message})}});
app.get("/api/creators",async(req,res)=>{const{data,error}=await supabase.from("creators").select("*").order("updated_at",{ascending:false});if(error)return res.status(500).json({success:false,error:error.message});res.json({success:true,creators:data.map(mapCreator)})});
app.patch("/api/creators/:id",async(req,res)=>{const p=req.body||{};const dbPatch={name:p.name,country:p.country,city:p.city,region:p.region,category:p.category,language:p.language,followers:p.followers,total_likes:p.totalLikes,video_count:p.videoCount,engagement:p.engagement,verified_status:p.verifiedStatus,influencer_current_state:p.influencerCurrentState,influencing_level:p.influencingLevel,admin_intelligence_note:p.adminIntelligenceNote,campaign_history:p.campaignHistory,trend_participation:p.trendParticipation,contact_email:p.contactEmail,contact_phone:p.contactPhone,contact_status:p.contactStatus,updated_at:new Date().toISOString()};Object.keys(dbPatch).forEach(k=>dbPatch[k]===undefined&&delete dbPatch[k]);const{data,error}=await supabase.from("creators").update(dbPatch).eq("id",req.params.id).select().single();if(error)return res.status(500).json({success:false,error:error.message});res.json({success:true,creator:mapCreator(data)})});
app.post("/api/sync-all",async(req,res)=>{const{data:creators}=await supabase.from("creators").select("*").eq("sync_mode","auto_10_min");const results=[];for(const creator of creators||[]){const scraped=await scrapeTikTok(creator.profile_url);const{data}=await supabase.from("creators").update(creatorPayload(creator.profile_url,scraped,creator)).eq("id",creator.id).select().single();if(data){await saveHistory(creator.id,scraped);await addSyncLog(creator.id,data.username,"scheduled_or_manual_sync",data.sync_status,scraped.message);results.push(mapCreator(data))}}res.json({success:true,results})});
app.get("/api/history/:id",async(req,res)=>{const{data,error}=await supabase.from("creator_metric_history").select("*").eq("creator_id",req.params.id).order("captured_at",{ascending:false}).limit(50);if(error)return res.status(500).json({success:false,error:error.message});res.json({success:true,history:data})});
app.get("/api/logs",async(req,res)=>{const{data,error}=await supabase.from("sync_logs").select("*").order("created_at",{ascending:false}).limit(100);if(error)return res.status(500).json({success:false,error:error.message});res.json({success:true,logs:data})});
app.post("/api/watchlist",async(req,res)=>{const{userEmail,creatorId,listName="Default Watchlist",note=""}=req.body||{};const{data,error}=await supabase.from("user_watchlists").insert({user_email:userEmail,creator_id:creatorId,list_name:listName,note}).select().single();if(error)return res.status(500).json({success:false,error:error.message});res.json({success:true,item:data})});
app.get("/api/watchlist/:email",async(req,res)=>{const{data,error}=await supabase.from("user_watchlists").select("*, creators(*)").eq("user_email",req.params.email).order("created_at",{ascending:false});if(error)return res.status(500).json({success:false,error:error.message});res.json({success:true,watchlist:data})});
app.delete("/api/watchlist/:id",async(req,res)=>{const{error}=await supabase.from("user_watchlists").delete().eq("id",req.params.id);if(error)return res.status(500).json({success:false,error:error.message});res.json({success:true})});
app.post("/api/search-usage",async(req,res)=>res.json({success:true}));
app.post("/api/campaigns",async(req,res)=>{const{data,error}=await supabase.from("campaigns").insert(req.body).select().single();if(error)return res.status(500).json({success:false,error:error.message});res.json({success:true,campaign:data})});
app.get("/api/campaigns",async(req,res)=>{const{data,error}=await supabase.from("campaigns").select("*").order("created_at",{ascending:false});if(error)return res.status(500).json({success:false,error:error.message});res.json({success:true,campaigns:data})});
app.post("/api/campaign-brief",async(req,res)=>{const{userEmail="",brandName="",campaignGoal="",country="Ethiopia",category="Food",budgetLevel="Medium"}=req.body||{};const generated_brief=`Campaign Brief for ${brandName||"Brand"}\nGoal: ${campaignGoal}\nCountry: ${country}\nCategory: ${category}\nBudget: ${budgetLevel}\n\nRecommended creator types:\n- High trust ${category} creators\n- Local creators in ${country}\n- Micro/mid creators with strong engagement\n\nExecution plan:\n1. Build a shortlist.\n2. Contact creators.\n3. Test 2 creative angles.\n4. Track weekly performance.`;const{data,error}=await supabase.from("campaign_briefs").insert({user_email:userEmail,brand_name:brandName,campaign_goal:campaignGoal,country,category,budget_level:budgetLevel,generated_brief}).select().single();if(error)return res.status(500).json({success:false,error:error.message});res.json({success:true,brief:data})});
app.post("/api/trends",async(req,res)=>{const{data,error}=await supabase.from("trends").insert(req.body).select().single();if(error)return res.status(500).json({success:false,error:error.message});res.json({success:true,trend:data})});
app.get("/api/trends",async(req,res)=>{const{data,error}=await supabase.from("trends").select("*").order("created_at",{ascending:false});if(error)return res.status(500).json({success:false,error:error.message});res.json({success:true,trends:data})});
cron.schedule("*/10 * * * *",async()=>{try{await fetch(`http://localhost:${process.env.PORT||5000}/api/sync-all`,{method:"POST"})}catch(e){console.log(e.message)}});
app.listen(process.env.PORT||5000,()=>console.log("AfriCreator V13 Fixed backend running"));
